server:
  port: 8082
nacos:
  address: 127.0.0.1:8848
dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://${nacos.address}
    username: nacos
    password: nacos
    group: fusion-center
  config-center:
    address: nacos://${nacos.address}
    group: fusion-center
    config-file: dubbo.properties # optional
    namespace: fusion-center
  provider:
    group: bff-server-dev
    version: 1.0.0
    timeout: 6000
    loadbalance: roundrobin
  application:
    qos-enable: true
    qos-port: 11111
  consumer:
    timeout: 6000
    version: 1.0.0
    group: bff-server-dev
    loadbalance: roundrobin
    trip:
      timeout: 6000
      version: 1.0.0
      group: trip-server-dev
      loadbalance: roundrobin
      application: trip-server
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://10.242.29.19:10372/boc_business?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=CST
          username: root
          password: eiVRPqZvWDoX
          driver-class-name: com.mysql.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        pool-name: OrderHikariPool
        is-auto-commit: true
        max-pool-size: 50
        min-idle: 5
        max-lifetime: 1800000
  redis:
    port: 32574
    host: 10.125.176.74
    jedis:
      pool:
        max-idle: 20
        max-active: 50
        min-idle: 5
        max-wait:
    timeout: 5000
    database: 12
    password: IOMredis#